### ISSUE TITLE
can not export wmv to mp4 

### ISSUE THREAD

**Issue by aanishacharyaa** [mifi/lossless-cut#1282]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Linux

### Steps to reproduce

any wmv video

### Expected behavior

should be able to change container to wmv to mp4

### Actual behavior

gives error : Could not find tag for codec wmapro in stream #0

### Share log

Error: Command failed with exit code 1: /tmp/.mount_Lossle7bT8sl/resources/ffmpeg -hide_banner -i x.wmv -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -default_mode infer_no_subs -ignore_unknown -f mp4 -y x -00.00.00.000-01.57.59.205.mp4
Input #0, asf, from 'x.wmv':
  Metadata:
    WMFSDKNeeded    : 0.0.0.0000
    DeviceConformanceTemplate: AP@L3
    WM/WMADRCPeakReference: 32767
    WM/WMADRCPeakTarget: 32767
    WM/WMADRCAverageReference: 2807
    WM/WMADRCAverageTarget: 2807
    WMFSDKVersion   : 11.0.5721.5275
    IsVBR           : 0
    artist          : m
    copyright       : m
  Duration: 01:57:59.21, start: 0.000000, bitrate: 5999 kb/s
  Stream #0:0: Audio: wmapro (b[1][0][0] / 0x0162), 44100 Hz, stereo, fltp, 256 kb/s
  Stream #0:1: Video: vc1 (Advanced) (WVC1 / 0x31435657), yuv420p, 1920x1080, 5744 kb/s, 30 fps, 30 tbr, 1k tbn
[mp4 @ 0x73cc040] Could not find tag for codec wmapro in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (/tmp/.mount_Lossle7bT8sl/resources/app.asar/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/tmp/.mount_Lossle7bT8sl/resources/app.asar/node_modules/execa/index.js:118:26)
    at async file:///tmp/.mount_Lossle7bT8sl/resources/app.asar/build/static/js/main.f18f3ad4.js:2:307402
    at async file:///tmp/.mount_Lossle7bT8sl/resources/app.asar/build/static/js/main.f18f3ad4.js:2:308170
    at async file:///tmp/.mount_Lossle7bT8sl/resources/app.asar/build/static/js/main.f18f3ad4.js:2:2382031

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "x.wmv",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "wmapro",
        "codec_long_name": "Windows Media Audio 9 Professional",
        "codec_type": "audio",
        "codec_tag_string": "b[1][0][0]",
        "codec_tag": "0x0162",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 7079205,
        "duration": "7079.205000",
        "bit_rate": "256032",
        "extradata_size": 18,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 1,
        "codec_name": "vc1",
        "codec_long_name": "SMPTE VC-1",
        "profile": "Advanced",
        "codec_type": "video",
        "codec_tag_string": "WVC1",
        "codec_tag": "0x31435657",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "pix_fmt": "yuv420p",
        "level": 3,
        "chroma_location": "left",
        "refs": 1,
        "r_frame_rate": "30/1",
        "avg_frame_rate": "30/1",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 7079205,
        "duration": "7079.205000",
        "bit_rate": "5744000",
        "extradata_size": 22,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "x.wmv": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "x.wmv",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "asf",
      "format_long_name": "ASF (Advanced / Active Streaming Format)",
      "start_time": "0.000000",
      "duration": "7079.205000",
      "size": "5309333011",
      "bit_rate": "5999920",
      "probe_score": 100,
      "tags": {
        "WMFSDKNeeded": "0.0.0.0000",
        "DeviceConformanceTemplate": "AP@L3",
        "WM/WMADRCPeakReference": "32767",
        "WM/WMADRCPeakTarget": "32767",
        "WM/WMADRCAverageReference": "2807",
        "WM/WMADRCAverageTarget": "2807",
        "WMFSDKVersion": "11.0.5721.5275",
        "IsVBR": "0",
        "artist": "m",
        "copyright": "m"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "linux",
  "version": "3.46.2"
}

**Comment by Grooves1210** [comment]
MP4 container doesn't support WMA, so converting container from your WMV video to MP4 isn't possible without transcoding the audio

From your log:
`[mp4 @ 0x73cc040] Could not find tag for codec wmapro in stream #0, codec not currently supported in container
`

For reference and codec/container compatibility see:  https://en.wikipedia.org/wiki/Comparison_of_video_container_formats
Note: WMV video is in an ASF container

**Comment by mifi** [comment]
Yea, see https://github.com/mifi/lossless-cut#re-encode-only-the-audio-track-keeping-the-lossless-video-track

I want losslesscut to give some kind of warning when trying to do this. Closing in favor of #547

**Comment by aanishacharyaa** [comment]
@mifi If when I followed https://github.com/mifi/lossless-cut#re-encode-only-the-audio-track-keeping-the-lossless-video-track  it says "Track 0 mismatch: codec_name mp3 != wmv1"

**Comment by mifi** [comment]
@aanishacharyaa Whoops I think those instructions are wrong! Merge is not the right tool to use. Instead open the mp3 audio file you just created and select "Include all tracks from the new file". I will update Readme
