### ISSUE TITLE
Trim OGG file

### ISSUE THREAD

**Issue by lamyergeier** [mifi/lossless-cut#1314]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

MacOS 12

### Steps to reproduce

Tried trimming ogg file

### Expected behavior

Export of Trimmed file

### Actual behavior

Failed

### Share log

Error: Command failed with exit code 1: /Applications/LosslessCut.app/Contents/Resources/ffmpeg -hide_banner -ss 17.60000 -i /Users/lamyergeier/Videos/Mobile/YouTube/Greater Good Science Center/20110823 - (609s)  Jack Kornfield - Forgiveness Meditation.opus -avoid_negative_ts make_zero -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map_metadata 0 -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f ogg -y /Users/lamyergeier/Videos/Mobile/YouTube/Greater Good Science Center/20110823 - (609s)  Jack Kornfield - Forgiveness Meditation-00.00.17.600-00.10.09.107.opus
[ogg @ 0x7fd6e9704380] 8690 bytes of comment header remain
Input #0, ogg, from '/Users/lamyergeier/Videos/Mobile/YouTube/Greater Good Science Center/20110823 - (609s)  Jack Kornfield - Forgiveness Meditation.opus':
  Duration: 00:10:09.11, start: 0.007500, bitrate: 101 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavf59.27.100
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x480 [SAR 1:1 DAR 4:3], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
[ogg @ 0x7fd6e9707180] Unsupported codec id in stream 1
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (/Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/execa/index.js:118:26)
    at async file:///Applications/LosslessCut.app/Contents/Resources/app.asar/build/static/js/main.f18f3ad4.js:2:307402
    at async file:///Applications/LosslessCut.app/Contents/Resources/app.asar/build/static/js/main.f18f3ad4.js:2:308170
    at async file:///Applications/LosslessCut.app/Contents/Resources/app.asar/build/static/js/main.f18f3ad4.js:2:2382031

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "/Users/lamyergeier/Videos/Mobile/YouTube/Greater Good Science Center/20110823 - (609s)  Jack Kornfield - Forgiveness Meditation.opus",
    "fileFormat": "ogg",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "opus",
        "codec_long_name": "Opus (Opus Interactive Audio Codec)",
        "codec_type": "audio",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 360,
        "start_time": "0.007500",
        "duration_ts": 29237160,
        "duration": "609.107500",
        "extradata_size": 19,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "eng",
          "encoder": "Lavf59.27.100"
        }
      },
      {
        "index": 1,
        "codec_name": "mjpeg",
        "codec_long_name": "Motion JPEG",
        "profile": "Baseline",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 640,
        "height": 480,
        "coded_width": 640,
        "coded_height": 480,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "4:3",
        "pix_fmt": "yuvj420p",
        "level": -99,
        "color_range": "pc",
        "color_space": "bt470bg",
        "chroma_location": "center",
        "refs": 1,
        "r_frame_rate": "90000/1",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 675,
        "start_time": "0.007500",
        "duration_ts": 54819675,
        "duration": "609.107500",
        "bits_per_raw_sample": "8",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 1,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "comment": "Cover (front)"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/Users/lamyergeier/Videos/Mobile/YouTube/Greater Good Science Center/20110823 - (609s)  Jack Kornfield - Forgiveness Meditation.opus": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 17.6
      }
    ],
    "mainFileFormatData": {
      "filename": "/Users/lamyergeier/Videos/Mobile/YouTube/Greater Good Science Center/20110823 - (609s)  Jack Kornfield - Forgiveness Meditation.opus",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "ogg",
      "format_long_name": "Ogg",
      "start_time": "0.007500",
      "duration": "609.107500",
      "size": "7698944",
      "bit_rate": "101117",
      "probe_score": 100
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "darwin",
  "version": "3.46.2"
}

**Comment by mifi** [comment]
did that work? can reopen if still a problem
