### ISSUE TITLE
Error: Command failed with exit code 1 depuis la version 3.43.0

### ISSUE THREAD

**Issue by dabipbip** [mifi/lossless-cut#1343]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Error: Command failed with exit code 1: F:\Downloads\resources\ffmpeg.exe -hide_banner -ss 479.82144 -i F:\video\Good Doctor.m2ts -t 6143.28762 -avoid_negative_ts make_zero -map 0:0 -c:0 copy -map 0:1 -c:1 copy -map 0:2 -c:2 copy -map 0:3 -c:3 copy -map 0:4 -c:4 mov_text -map_metadata 0 -movflags +faststart -default_mode infer_no_subs -ignore_unknown -f mov -y F:\video\Good Doctor-00.07.59.821-01.50.23.109.mov
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[aac @ 000001a87687ec40] Multiple frames in a packet.
[h264 @ 000001a87687d480] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001a87687d480] decode_slice_header error
[h264 @ 000001a87687d480] no frame!
[mpegts @ 000001a87687c000] PES packet size mismatch
[mpegts @ 000001a87687c000] Packet corrupt (stream = 0, dts = 1537401998).
[mpegts @ 000001a87687c000] PES packet size mismatch
[mpegts @ 000001a87687c000] Packet corrupt (stream = 2, dts = 1537349798).
[mpegts @ 000001a87687c000] PES packet size mismatch
[mpegts @ 000001a87687c000] Packet corrupt (stream = 3, dts = 1537364198).
[mpegts @ 000001a87687c000] PES packet size mismatch
[mpegts @ 000001a87687c000] Packet corrupt (stream = 0, dts = 1537401998).
[mpegts @ 000001a87687c000] PES packet size mismatch
[mpegts @ 000001a87687c000] Packet corrupt (stream = 0, dts = 1537401998).
Input #0, mpegts, from 'F:\video\Good Doctor.m2ts':
  Duration: 02:01:00.25, start: 9822.115111, bitrate: 4747 kb/s
  Program 42467 
  Stream #0:0[0x6e]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(top first), 1440x1080 [SAR 4:3 DAR 16:9], 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x78](fra): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 137 kb/s
  Stream #0:2[0x79](qaa): Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 65 kb/s
  Stream #0:3[0x7a](qad): Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 49 kb/s
  Stream #0:4[0x82](fra,fra): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
  Stream #0:3 -> #0:3 (copy)
  Stream #0:4 -> #0:4 (? (?) -> mov_text (native))
Decoder (codec dvb_teletext) not found for input stream #0:4
    at makeError (F:\Downloads\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (F:\Downloads\resources\app.asar\node_modules\execa\index.js:118:26)
    at async file:///F:/Downloads/resources/app.asar/build/static/js/main.ff7aecec.js:2:307871
    at async file:///F:/Downloads/resources/app.asar/build/static/js/main.ff7aecec.js:2:308737
    at async file:///F:/Downloads/resources/app.asar/build/static/js/main.ff7aecec.js:2:2386227

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "F:\\video\\Good Doctor.m2ts",
    "fileFormat": "mov",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "[27][0][0][0]",
        "codec_tag": "0x001b",
        "width": 1440,
        "height": 1080,
        "coded_width": 1440,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "4:3",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "chroma_location": "left",
        "field_order": "tt",
        "refs": 1,
        "is_avc": "false",
        "nal_length_size": "0",
        "id": "0x6e",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/90000",
        "start_pts": 884049760,
        "start_time": "9822.775111",
        "duration_ts": 653363038,
        "duration": "7259.589311",
        "bits_per_raw_sample": "8",
        "extradata_size": 38,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "[15][0][0][0]",
        "codec_tag": "0x000f",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x78",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 884012680,
        "start_time": "9822.363111",
        "duration_ts": 653334718,
        "duration": "7259.274644",
        "bit_rate": "130504",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "fra"
        }
      },
      {
        "index": 2,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "HE-AAC",
        "codec_type": "audio",
        "codec_tag_string": "[15][0][0][0]",
        "codec_tag": "0x000f",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x79",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 884028520,
        "start_time": "9822.539111",
        "duration_ts": 653325118,
        "duration": "7259.167978",
        "bit_rate": "65417",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "qaa"
        }
      },
      {
        "index": 3,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "HE-AAC",
        "codec_type": "audio",
        "codec_tag_string": "[15][0][0][0]",
        "codec_tag": "0x000f",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x7a",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 884042920,
        "start_time": "9822.699111",
        "duration_ts": 653325118,
        "duration": "7259.167978",
        "bit_rate": "49581",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "qad"
        }
      },
      {
        "index": 4,
        "codec_name": "dvb_teletext",
        "codec_long_name": "DVB teletext",
        "codec_type": "subtitle",
        "codec_tag_string": "[6][0][0][0]",
        "codec_tag": "0x0006",
        "id": "0x82",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 883990360,
        "start_time": "9822.115111",
        "duration_ts": 653345038,
        "duration": "7259.389311",
        "extradata_size": 4,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "fra,fra"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "F:\\video\\Good Doctor.m2ts": {
        "0": true,
        "1": true,
        "2": true,
        "3": true,
        "4": true
      }
    },
    "cutSegments": [
      {
        "start": 479.82143986998915,
        "end": 6623.109055254604
      }
    ],
    "mainFileFormatData": {
      "filename": "F:\\video\\Good Doctor.m2ts",
      "nb_streams": 5,
      "nb_programs": 1,
      "format_name": "mpegts",
      "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
      "start_time": "9822.115111",
      "duration": "7260.249311",
      "size": "4308440640",
      "bit_rate": "4747429",
      "probe_score": 50
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge"
  },
  "platform": "win32",
  "version": "3.47.1"
}

### Expected behavior

Losslesscut ne fonctionne plus apres la version 3.43.0

### Actual behavior

Losslesscut no longer works after version 3.43.0 sous windows 10 ou linux

**Comment by mifi** [comment]
`Decoder (codec dvb_teletext) not found for input stream #0:4`
try to disable the dvb_teletext track (index 4)
