### ISSUE TITLE
Smart cut doesn't work using a different build of ffmpeg

### ISSUE THREAD

**Issue by xd-mau5** [mifi/lossless-cut#1430]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
- [X] If you have an issue only with one particular file, [use this form instead](https://github.com/mifi/lossless-cut/issues/new?assignees=&labels=&template=file-issue.yml)

### Operating System

Windows 10

### Steps to reproduce

Try to export the video, goes to 50%, throws error

### Expected behavior

Export the video without a issue, in the previous version this didn't happen

### Actual behavior

Throws error

### Share log

```
Error: Command failed with exit code 1: C:\Users\elect\scoop\apps\ffmpeg-gyan-nightly\current\bin\ffmpeg.exe -hide_banner -f concat -safe 0 -protocol_whitelist file,pipe -i - -i C:\Users\elect\Desktop\danser_2023-01-19_11-07-34-smartcut-segment-copy-0.mp4 -map 0:0 -c:0 copy -disposition:0 default -map 0:1 -c:1 copy -disposition:1 default -map_metadata 1 -movflags use_metadata_tags -movflags +faststart -default_mode infer_no_subs -ignore_unknown -strict experimental -video_track_timescale 15360 -f mp4 -y C:\Users\elect\Desktop\danser_2023-01-19_11-07-34.mp4
[fd @ 000002f8490f4b00] Protocol 'fd' not on whitelist 'file,pipe'!
fd:: Invalid argument
    at makeError (C:\Users\elect\scoop\apps\losslesscut\3.49.0\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\elect\scoop\apps\losslesscut\3.49.0\resources\app.asar\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "D:\\Users\\Omar\\Videos\\Osu!\\danser_2023-01-19_11-07-34.mp4",
    "fileFormat": "mp4",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1080,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "id": "0x1",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "60/1",
        "time_base": "1/15360",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 5945600,
        "duration": "387.083333",
        "bit_rate": "2992147",
        "bits_per_raw_sample": "8",
        "nb_frames": "23225",
        "extradata_size": 61,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]",
          "encoder": "Lavc59.56.100 h264_qsv"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x2",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 18579600,
        "duration": "387.075000",
        "bit_rate": "196949",
        "nb_frames": "18146",
        "extradata_size": 5,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\Users\\Omar\\Videos\\Osu!\\danser_2023-01-19_11-07-34.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 272.019147
      }
    ],
    "mainFileFormatData": {
      "filename": "D:\\Users\\Omar\\Videos\\Osu!\\danser_2023-01-19_11-07-34.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "387.084000",
      "size": "154864627",
      "bit_rate": "3200641",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf59.35.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "merge",
    "outSegTemplate": "${FILENAME}${EXT}"
  },
  "platform": "win32",
  "version": "3.49.0"
}
```

**Comment by mifi** [comment]
- does it work with the version of ffmpeg built into losslesscut?
- why do you need to run on a different build of ffmpeg?
- which version of ffmpeg are you using?

**Comment by xd-mau5** [comment]
> * does it work with the version of ffmpeg built into losslesscut?
> * why do you need to run on a different build of ffmpeg?
> * which version of ffmpeg are you using?

- It works with the built into lossless cut
- I just do it because i have ffmpeg in my device from a long time and having two builds is a waste of space
- Latest version of ffmpeg-gyan-nightly

**Comment by mifi** [comment]
I'm probably not going to spend much time on trying to fix an issue with a nightly ffmpeg build. However if it turns out to be an issue with a future stable ffmpeg version we can reopen this. I think I can only recommend using a stable ffmpeg version like 5.1.2 from https://ffmpeg.org/download.html
