### ISSUE TITLE
Zero-file as output

### ISSUE THREAD

**Issue by densu90** [mifi/lossless-cut#1679]
### I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

trying to cut some particular files
(issue is file-dependent)

### Expected behavior

export part of file

### Actual behavior

creating zero-file (304 bytes) with expected name and throw an error message. if try mp4 as output - creates expected-sized file which can not be opened:

--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: Unknown GUID Name {08E22ADA-B715-45ED-9D20-7B87750301D4}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0

Media Type 1:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0

### Provide an error report

Error: Command failed with exit code 1: T:\1\LosslessCut-win-x64\resources\ffmpeg.exe -hide_banner -ss 384.72000 -i T:\1\1.mkv -t 419.84000 -avoid_negative_ts make_zero -map 0:0 -c:0 copy -map_metadata 0 -default_mode infer_no_subs -ignore_unknown -f matroska -y T:\1\1-00.06.24.720-00.13.24.560.mkv
Input #0, matroska,webm, from 'T:\1\1.mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
    creation_time   : 2023-08-13T06:55:59.000000Z
  Duration: 00:39:05.48, start: 0.000000, bitrate: 195 kb/s
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 320x240, SAR 1:1 DAR 4:3, 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      BPS             : 193559
      DURATION        : 00:39:05.480000000
      NUMBER_OF_FRAMES: 58636
      NUMBER_OF_BYTES : 56748764
      _STATISTICS_WRITING_APP: mkvmerge v77.0 ('Elemental') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-08-13 06:55:59
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
Error initializing output stream 0:0 -- 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
    at makeError (T:\1\LosslessCut-win-x64\resources\app.asar\node_modules\execa\lib\error.js:60:11)
    at handlePromise (T:\1\LosslessCut-win-x64\resources\app.asar\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": false,
    "preserveMetadataOnMerge": false,
    "filePath": "T:\\1\\1.mkv",
    "fileFormat": "matroska",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "hevc",
        "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
        "profile": "Main",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 320,
        "height": 240,
        "coded_width": 320,
        "coded_height": 240,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "4:3",
        "pix_fmt": "yuv420p",
        "level": 60,
        "color_range": "tv",
        "chroma_location": "center",
        "refs": 1,
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "extradata_size": 110,
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        },
        "tags": {
          "BPS": "193559",
          "DURATION": "00:39:05.480000000",
          "NUMBER_OF_FRAMES": "58636",
          "NUMBER_OF_BYTES": "56748764",
          "_STATISTICS_WRITING_APP": "mkvmerge v77.0 ('Elemental') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2023-08-13 06:55:59",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "T:\\1\\1.mkv": {
        "0": true
      }
    },
    "cutSegments": [
      {
        "end": 384.72
      },
      {
        "start": 384.72,
        "end": 804.56
      },
      {
        "start": 804.56
      }
    ],
    "mainFileFormatData": {
      "filename": "T:\\1\\1.mkv",
      "nb_streams": 1,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.000000",
      "duration": "2345.480000",
      "size": "57277920",
      "bit_rate": "195364",
      "probe_score": 100,
      "tags": {
        "encoder": "libebml v1.4.4 + libmatroska v1.7.1",
        "creation_time": "2023-08-13T06:55:59.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate",
    "outSegTemplate": "${FILENAME}-${CUT_FROM}-${CUT_TO}${SEG_SUFFIX}${EXT}"
  },
  "platform": "win32",
  "version": "3.54.0"
}

**Comment by mifi** [comment]
hi. `Invalid data found when processing input` usually means the file has some corruption or error in its data. Does the file play back in losslesscut or other video players like windows media player?

**Comment by densu90** [comment]
hi. yes, file is playable. in the directcut interface including. i cannot exclude that it have some corruption, yet it is not noticeable while playback.
can an option "proceed on your own risk" be added to bypass the issue if occur?
thx!
________________________________
Від: Mikael Finstad ***@***.***>
Надіслано: 14 серпня 2023 р. 12:22
Кому: mifi/lossless-cut ***@***.***>
Копія: densu90 ***@***.***>; Author ***@***.***>
Тема: Re: [mifi/lossless-cut] Zero-file as output (Issue #1679)


hi. Invalid data found when processing input usually means the file has some corruption or error in its data. Does the file play back in losslesscut or other video players like windows media player?

**Comment by mifi** [comment]
The problem is that ffmpeg doesn't accept the file at all, it's a fatal error that causes ffmpeg to not be able to process the file, hence the encoding fails: 

```
Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
```

So it's not possible to "bypass" the issue. There's probably a bug in ffmpeg and/or some issue with your file. Not sure if there's anything to do other than report the issue to ffmpeg with a sample file to reproduce it https://trac.ffmpeg.org/
