### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jacobjake1** [mifi/lossless-cut#1901]
.

**Comment by jacobjake1** [comment]
userOpenFiles Error: Unsupported file: Command failed with exit code 1: C:\Users\jacob\AppData\Local\Temp\Rar$EXa5332.24229\resources\ffprobe.exe -of json -show_chapters -show_format -show_entries stream -i D:\DCIM\100GOPRO\GH010007.MP4 -hide_banner
'C:\Users\jacob\AppData\Local\Temp\Rar$EXa5332.24229\resources\ffprobe.exe' is not recognized as an internal or external command,
operable program or batch file.
    at tf (index-18074aaf.js:160:40347)
    at async index-18074aaf.js:298:31104
    at async index-18074aaf.js:298:33126
    at async index-18074aaf.js:299:1111
(anonymous) @ index-18074aaf.js:299
