### ISSUE TITLE
Can't open BVR files saved by BlueIris surveylance package

### ISSUE THREAD

**Issue by sambul13** [mifi/lossless-cut#2160]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Try with a different kind of file to confirm that the problem is related to just this file.
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md)
- [X] Search for your problem under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Steps to reproduce

Open a BVR file (container). LosslessCut can't recognize it.

### Expected behavior

Pls enable playback and usual editing features of LosslessCut, possibly with lossless conversion to H264.

### Actual behavior

Won't play BVR. Note that BlueIris package can play it without frame view, _VLC --demux h264_ command [can play](https://forum.videolan.org/viewtopic.php?t=144133) it and view forward frames with E, also MPV player can play it and view forward frames with . The BlueIris package and its BVR format are massively used, and LosslessCut ability to view and extract frames would be highly appreciated. 

### Provide an error report

No error occurred.

{
  "err": false,
  "state": {
    "ffmpegExperimental": false,
    "preserveMovData": false,
    "movFastStart": true,
    "preserveMetadataOnMerge": false,
    "filePath": "C:\\Users\\UserName\\Downloads\\Zemicam.20240918_100810.bvr",
    "fileFormat": "h264",
    "externalFilesMeta": {},
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Constrained Baseline",
        "codec_type": "video",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 2592,
        "height": 1944,
        "coded_width": 2592,
        "coded_height": 1944,
        "closed_captions": 0,
        "film_grain": 0,
        "has_b_frames": 0,
        "pix_fmt": "yuv420p",
        "level": 50,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "false",
        "nal_length_size": "0",
        "r_frame_rate": "15/1",
        "avg_frame_rate": "15/1",
        "time_base": "1/1200000",
        "bits_per_raw_sample": "8",
        "extradata_size": 36,
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0,
          "captions": 0,
          "descriptions": 0,
          "metadata": 0,
          "dependent": 0,
          "still_image": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\UserName\\Downloads\\Zemicam.20240918_100810.bvr": {
        "0": true
      }
    },
    "cutSegments": [
      {}
    ],
    "mainFileFormatData": {
      "filename": "C:\\Users\\UserName\\Downloads\\Zemicam.20240918_100810.bvr",
      "nb_streams": 1,
      "nb_programs": 0,
      "format_name": "h264",
      "format_long_name": "raw H.264 video",
      "size": "1077511386",
      "probe_score": 51
    },
    "rotation": 360,
    "shortestFlag": false,
    "effectiveExportMode": "separate"
  },
  "platform": "win32",
  "version": "3.62.0"
}

### Share the file

https://www.dropbox.com/scl/fi/u41dcd3bcfobt0eza9c4e/USB_Cam_8mm.bvr?rlkey=nupw0faei8lt0n980iqq8k95b&st=rxumxijb&dl=0

### Share log from developer tools

Version 3.62.0
App.tsx:1960 userOpenFiles
App.tsx:1961 C:\Users\UserName\Downloads\Zemicam.20240918_100810.bvr
App.tsx:1615 loadMedia C:\Users\Username\Downloads\Zemicam.20240918_100810.bvr undefined undefined
App.tsx:804 State reset
App.tsx:2398 onVideoError DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed 4
(anonymous) @ App.tsx:2398
App.tsx:2413 Trying to create preview
App.tsx:2422 Error: Invalid duration
    at App.tsx:2415:66
(anonymous) @ App.tsx:2422
useKeyframes.ts:50 Failed to read keyframes Error: Command failed with exit code 1: E:\Software\Windows\Media\Video\LosslessCut-win-x64\resources\ffprobe.exe -v error -read_intervals 0%30 -show_packets -select_streams 0 -show_entries packet=pts_time,flags -of json C:\Users\UserName\Downloads\Zemicam.20240918_100810.bvr
[NULL @ 000001ef849bdc80] too many reference frames 32
[NULL @ 000001ef849bdc80] sps_id 32 out of range
[NULL @ 000001ef849bdc80] too many reference frames 32
[NULL @ 000001ef849bdc80] sps_id 32 out of range
Could not seek to position 0: Operation not permitted
Could not read packets in interval id:0 start:0 end:30
{
    "packets": [

    ]
}
    at makeError (E:\Software\Windows\Media\Video\LosslessCut-win-x64\resources\app.asar\out\main\index.js:1816:13)
    at handlePromise (E:\Software\Windows\Media\Video\LosslessCut-win-x64\resources\app.asar\out\main\index.js:2635:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.runFfprobe (E:\Software\Windows\Media\Video\LosslessCut-win-x64\resources\app.asar\out\main\index.js:2784:12)

**Comment by mifi** [comment]
Does it work if you File -> convert to supported format?

**Comment by sambul13** [comment]
Hi mifi,

Fastest conversion doesn't work at all, Fast shows picture on screen but can't play the video or neither show frames, Slow works jumpy at low quality with no audio, Slowest takes forever to encode a very small file so I stopped it eventually.

**Comment by mifi** [comment]
I see that BVR files are really just RAW H264. That means it's just a stream of H264 frames, and there is no metadata like FPS, duration etc.

Unfortunately LosslessCut does not work with files that do not have any duration, and it's not trivial to fix this, so LosslessCut doesn't support raw H264, H265 etc.

What you can do is to run this ffmpeg command first, in order to specify the FPS and mux it into a "proper" format:
```bash
ffmpeg -r 30 -i input.bvr -c copy out.mp4
```

Note that `-r` specifies the frame rate. You need to find the correct frame rate that the camera actually records with and use that.

`out.mp4` will now have a valid FPS and a duration and you should be able to open it in Losslesscut and edit it.

LosslessCut could in theory prompt the user for an FPS input and then do this, but this seems like a very niche use case (this is the first time I've heard someone trying to open raw h264), so I'm probably not going to prioritize it soon.
