### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by mcarn** [mifi/lossless-cut#312]
Error: EPERM: operation not permitted, rename 'C:\Users\mcarnerm\AppData\Roaming\LosslessCut\config.json.919399885' -> 'C:\Users\mcarnerm\AppData\Roaming\LosslessCut\config.json'
    at Object.renameSync (fs.js:643:3)
    at Function.writeFileSync [as sync] (C:\Users\mcarnerm\Desktop\nodeapp\randomstuff\LosslessCut-win\resources\app.asar\node_modules\write-file-atomic\index.js:200:8)
    at ElectronStore._write (C:\Users\mcarnerm\Desktop\nodeapp\randomstuff\LosslessCut-win\resources\app.asar\node_modules\conf\index.js:180:21)
    at ElectronStore.set store [as store] (C:\Users\mcarnerm\Desktop\nodeapp\randomstuff\LosslessCut-win\resources\app.asar\node_modules\conf\index.js:461:8)
    at ElectronStore.set (C:\Users\mcarnerm\Desktop\nodeapp\randomstuff\LosslessCut-win\resources\app.asar\node_modules\conf\index.js:339:14)
    at file:///C:/Users/mcarnerm/Desktop/nodeapp/randomstuff/LosslessCut-win/resources/app.asar/build/static/js/main.42d2a25f.chunk.js:1:102324
    at ds (file:///C:/Users/mcarnerm/Desktop/nodeapp/randomstuff/LosslessCut-win/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:624679)
    at Oc (file:///C:/Users/mcarnerm/Desktop/nodeapp/randomstuff/LosslessCut-win/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:649492)
    at t.unstable_runWithPriority (file:///C:/Users/mcarnerm/Desktop/nodeapp/randomstuff/LosslessCut-win/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:667354)
    at Ui (file:///C:/Users/mcarnerm/Desktop/nodeapp/randomstuff/LosslessCut-win/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:592123)

{
  "err": {
    "code": "EPERM"
  }
}

This is my current Lossless cut folder
![image](https://user-images.githubusercontent.com/28352648/79440288-b6caf900-7fcd-11ea-8a53-c0981afa46b9.png)

**Comment by mifi** [comment]
1. What were you doing when you got this error?
2. Does it happen all the time?
3. Which version are you using?

**Comment by mcarn** [comment]
Hi,
I had installed the 3.17.1 version, updated by donwloading the newest pre-release 3.19.0, and since then I can't do anything, the first thing appearing in the screen is the error

![image](https://user-images.githubusercontent.com/28352648/79488832-41354c00-8012-11ea-80f9-84e89b744ef9.png)


Re-checking now (1minute after the screenshot from above was taken), the error is gone.

**Comment by mifi** [comment]
Ok will have to look in to this. Damn Windows, always the one causing problems 😅

**Comment by chaveezy** [comment]
Been tracking this same electron-store issue on my app, which checks several local application version files against network files.  I reduced the amount of writes to the json file (store.set) and it has gone away completely.   At least I have not had any reports in the last two weeks.

**Comment by mifi** [comment]
Yea, my code is doing a lot of successive `store.set` operations. I suppose I just need to batch them and maybe debounce 🙁 I just hate the fact that every developer should have to go through this and then realise they need to rewrite their code after a user has discovered the error...
