### ISSUE TITLE
exports number expected

### ISSUE THREAD

**Issue by calmosono** [mifi/lossless-cut#313]
opening a webm file:
`TypeError: Expected a finite number
    at e.exports (file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:493887)
    at file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/main.f2afc881.chunk.js:1:69612
    at Array.map (<anonymous>)
    at file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/main.f2afc881.chunk.js:1:68621
    at lo (file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:606139)
    at Yo (file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:614404)
    at qo (file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:614223)
    at _s (file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:654877)
    at mc (file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:636978)
    at pc (file:///tmp/.mount_Losslewd3eot/resources/app.asar/build/static/js/2.84de25ef.chunk.js:2:636903)

{
  "err": {}
}`

**Comment by calmosono** [comment]
First time I use LosslessCut and open a file I get this issue

**Comment by mifi** [comment]
Ahh I got this error too, have fixed it, fix will be included in newest version
