### ISSUE TITLE
Allow experimental ffmpeg features

### ISSUE THREAD

**Issue by ChildishGiant** [mifi/lossless-cut#336]
Surely it should be able to just change the container?
To do it with ffmpeg I needed to add `-strict -2` but it has to come in the right order
```
Error: Command failed with exit code 1: C:\Users\allie\AppData\Local\Temp\1b7ElG9v0KbzGqmiXlnKEWdwI1y\resources\node_modules\ffmpeg-static\ffmpeg.exe -hide_banner -i D:\merged.mkv -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f mp4 -y C:\Users\allie\Videos\merged-00.00.00.000-02.26.13.710.mp4
Input #0, matroska,webm, from 'D:\merged.mkv':
  Metadata:
    ENCODER         : Lavf58.36.100
  Duration: 02:26:13.71, start: 0.000000, bitrate: 765 kb/s
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 854x480 [SAR 1:1 DAR 427:240], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc.
      DURATION        : 02:26:13.667000000
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 02:26:13.711000000
[mp4 @ 0000021db2903a40] track 1: codec frame size is not set
[mp4 @ 0000021db2903a40] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\allie\AppData\Local\Temp\1b7ElG9v0KbzGqmiXlnKEWdwI1y\resources\app.asar\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\allie\AppData\Local\Temp\1b7ElG9v0KbzGqmiXlnKEWdwI1y\resources\app.asar\node_modules\execa\index.js:114:26)
    at async R (file:///C:/Users/allie/AppData/Local/Temp/1b7ElG9v0KbzGqmiXlnKEWdwI1y/resources/app.asar/build/static/js/main.2a754899.chunk.js:1:4175)
    at async I (file:///C:/Users/allie/AppData/Local/Temp/1b7ElG9v0KbzGqmiXlnKEWdwI1y/resources/app.asar/build/static/js/main.2a754899.chunk.js:1:4836)
    at async file:///C:/Users/allie/AppData/Local/Temp/1b7ElG9v0KbzGqmiXlnKEWdwI1y/resources/app.asar/build/static/js/main.2a754899.chunk.js:1:124457

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "D:\\merged.mkv",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Main",
        "codec_type": "video",
        "codec_time_base": "1001/60000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 854,
        "height": 480,
        "coded_width": 864,
        "coded_height": 480,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "427:240",
        "pix_fmt": "yuv420p",
        "level": 31,
        "chroma_location": "left",
        "field_order": "progressive",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30000/1001",
        "avg_frame_rate": "30000/1001",
        "time_base": "1/1000",
        "start_pts": 215,
        "start_time": "0.215000",
        "bits_per_raw_sample": "8",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "HANDLER_NAME": "ISO Media file produced by Google Inc.",
          "DURATION": "02:26:13.667000000"
        }
      },
      {
        "index": 1,
        "codec_name": "opus",
        "codec_long_name": "Opus (Opus Interactive Audio Codec)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "DURATION": "02:26:13.711000000"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\merged.mkv": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            193.8757751993952,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "64a075e0-de5a-4ba2-b51f-25c438166283"
      }
    ],
    "fileFormatData": {
      "filename": "D:\\merged.mkv",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.000000",
      "duration": "8773.711000",
      "size": "839286672",
      "bit_rate": "765274",
      "probe_score": 100,
      "tags": {
        "ENCODER": "Lavf58.36.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}
```

**Comment by bouscram** [comment]
I think the issue is that the Opus audio codec is normally not supported in .mp4 containers. Apparently ffmpeg allows it with the options you mention, but is it supported in players ?

**Comment by mifi** [comment]
Yea, I don't think we should default to `-strict -2` globally. Maybe you can just copy the ffmpeg command under "Help" and add these flags?

**Comment by mifi** [comment]
Have now added an Experimental flag under Settings
