### ISSUE TITLE
Failed build on MacOS Catalina

### ISSUE THREAD

**Issue by jdmuys** [mifi/lossless-cut#343]
TL;DR: I followed the instructions in developer-notes.md, and I now have the following error message: 

   Uncaught Error: Cannot find module './locale'

Note: I am noob, with no Electron experience. I am willing to learn, but would need pointers.

Details:
1- I updated Homebrew, and brew installed yarn 1.22.4, which installed node 14.1.0

2- I did `npm install`, which did quite a few things (170 lines of output included some deprecation warnings), and ended with:

```
   added 2152 packages from 1368 contributors and audited 935980 packages in 187.825s
   [...]
   found 3 low severity vulnerabilities
```

3- tried to run `npm run watch`. it failed instantly with "npm ERR! missing script: watch"

4- tried to run `npm start`. This kind of worked, with the terminal warning:

   [0] ./node_modules/moment/src/lib/locale/locales.js
   [0] Module not found: Can't resolve './locale' in '/Users/jdmuys/devt/lossless-cut/node_modules/moment/src/lib/locale'

5- Electron launched, and the window shows only the missing locale error. Here is the output of the Javascript console:

```
prototype.js:1 Uncaught Error: Cannot find module './locale'
    at webpackMissingModule (prototype.js:1)
    at Module../node_modules/moment/src/lib/moment/prototype.js (prototype.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../node_modules/moment/src/lib/moment/moment.js (moment.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../node_modules/moment/src/moment.js (moment.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/ffmpeg.js (ffmpeg.js:1)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module.<anonymous> (CanvasPlayer.js:1)
    at Module../src/CanvasPlayer.js (CanvasPlayer.js:105)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/Canvas.jsx (App.jsx:2056)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/App.jsx (main.css:7)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Module../src/index.jsx (i18n.js:67)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (util.js:207)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
security-warnings.ts:161 Electron Security Warning (Disabled webSecurity) This renderer process has "webSecurity" disabled. This
  exposes users of this app to severe security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
warnAboutDisabledWebSecurity @ security-warnings.ts:161
security-warnings.ts:196 Electron Security Warning (allowRunningInsecureContent) This renderer process has "allowRunningInsecureContent"
  enabled. This exposes users of this app to severe security risks.

  
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
warnAboutInsecureContentAllowed @ security-warnings.ts:196
security-warnings.ts:179 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ security-warnings.ts:179
webpackHotDevClient.js:138 ./node_modules/moment/src/lib/locale/locales.js
Module not found: Can't resolve './locale' in '/Users/jdmuys/devt/lossless-cut/node_modules/moment/src/lib/locale'
printWarnings @ webpackHotDevClient.js:138

![image](https://user-images.githubusercontent.com/101319/80926499-911f4d00-8d4c-11ea-9570-66e5514fc383.png)
```

**Comment by mifi** [comment]
Opps those notes are a bit outdated. Try `rm -rf node_modules` then `yarn` And then npm start.
No need for watch

**Comment by jdmuys** [comment]
`rm -rf node_modules` succeeded, but npm start failed:

```
$ npm start

> lossless-cut@3.22.0 start /Users/jdmuys/devt/lossless-cut
> concurrently -k "BROWSER=none PORT=3001 react-scripts start" "wait-on http://localhost:3001 && electron ."

sh: concurrently: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! lossless-cut@3.22.0 start: `concurrently -k "BROWSER=none PORT=3001 react-scripts start" "wait-on http://localhost:3001 && electron ."`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lossless-cut@3.22.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jdmuys/.npm/_logs/2020-05-04T05_58_16_140Z-debug.log
```
The content of that log file is:

```
$ cat /Users/jdmuys/.npm/_logs/2020-05-04T05_58_16_140Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/14.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v14.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lossless-cut@3.22.0~prestart: lossless-cut@3.22.0
6 info lifecycle lossless-cut@3.22.0~start: lossless-cut@3.22.0
7 verbose lifecycle lossless-cut@3.22.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle lossless-cut@3.22.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jdmuys/devt/lossless-cut/node_modules/.bin:/opt/facebook/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/facebook/ops/scripts/chef:/opt/homebrew/bin:/usr/local/munki:/opt/facebook/hg/bin:/Library/Apple/usr/bin:/opt/android_sdk/tools:/opt/android_sdk/platform-tools
9 verbose lifecycle lossless-cut@3.22.0~start: CWD: /Users/jdmuys/devt/lossless-cut
10 silly lifecycle lossless-cut@3.22.0~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'concurrently -k "BROWSER=none PORT=3001 react-scripts start" "wait-on http://localhost:3001 && electron ."'
10 silly lifecycle ]
11 info lifecycle lossless-cut@3.22.0~start: Failed to exec start script
12 verbose stack Error: lossless-cut@3.22.0 start: `concurrently -k "BROWSER=none PORT=3001 react-scripts start" "wait-on http://localhost:3001 && electron ."`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1051:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid lossless-cut@3.22.0
14 verbose cwd /Users/jdmuys/devt/lossless-cut
15 verbose Darwin 19.4.0
16 verbose argv "/usr/local/Cellar/node/14.1.0/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v14.1.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error lossless-cut@3.22.0 start: `concurrently -k "BROWSER=none PORT=3001 react-scripts start" "wait-on http://localhost:3001 && electron ."`
23 error spawn ENOENT
24 error Failed at the lossless-cut@3.22.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by mifi** [comment]
```bash
npx react-scripts build && npx electron-builder
```

**Comment by mifi** [comment]
Did you succeed? If so maybe we can close?
