### ISSUE TITLE
Not allowing me to export

### ISSUE THREAD

**Issue by SpencerBuff6633** [mifi/lossless-cut#373]
It isn't letting me export my file
Error: Command failed with ENOENT: C:\Users\Spencer\AppData\Local\Temp\1bWVyP4la8vZLD1ks8urbKRUcXo\resources\node_modules\ffmpeg-static\ffmpeg.exe -hide_banner -ss 1.70000 -i C:\Users\Spencer\Desktop\Stream Videos\Call of Duty  Modern Warfare 2019\Call of Duty  Modern Warfare 2019 2020.05.15 - 22.44.39.01.mp4 -t 26.24800 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f mp4 -y C:\Users\Spencer\Desktop\Stream Videos\Call of Duty  Modern Warfare 2019\Call of Duty  Modern Warfare 2019 2020.05.15 - 22.44.39.01-00.00.01.700-00.00.27.948.mp4
spawn C:\Users\Spencer\AppData\Local\Temp\1bWVyP4la8vZLD1ks8urbKRUcXo\resources\node_modules\ffmpeg-static\ffmpeg.exe ENOENT
The system cannot find the path specified.
    at notFoundError (C:\Users\Spencer\AppData\Local\Temp\1bWVyP4la8vZLD1ks8urbKRUcXo\resources\app.asar\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Spencer\AppData\Local\Temp\1bWVyP4la8vZLD1ks8urbKRUcXo\resources\app.asar\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Spencer\AppData\Local\Temp\1bWVyP4la8vZLD1ks8urbKRUcXo\resources\app.asar\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

{
  "err": {
    "code": "ENOENT",
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false
  },
  "state": {
    "filePath": "C:\\Users\\Spencer\\Desktop\\Stream Videos\\Call of Duty  Modern Warfare 2019\\Call of Duty  Modern Warfare 2019 2020.05.15 - 22.44.39.01.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "16189984/1941732601",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "smpte170m",
        "color_transfer": "bt470m",
        "color_primaries": "smpte170m",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "60/1",
        "avg_frame_rate": "2095002198/34935863",
        "time_base": "1/90000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 801799727,
        "duration": "8908.885856",
        "bit_rate": "45984650",
        "bits_per_raw_sample": "8",
        "nb_frames": "534240",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-05-16T07:13:09.000000Z",
          "language": "und",
          "handler_name": "VideoHandle"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 427632960,
        "duration": "8909.020000",
        "bit_rate": "196989",
        "max_bit_rate": "96000",
        "nb_frames": "417527",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2020-05-16T07:13:09.000000Z",
          "language": "und",
          "handler_name": "SoundHandle"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\Spencer\\Desktop\\Stream Videos\\Call of Duty  Modern Warfare 2019\\Call of Duty  Modern Warfare 2019 2020.05.15 - 22.44.39.01.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 27.948,
        "end": 36.47,
        "name": "cut",
        "color": {
          "model": "hsv",
          "color": [
            158.48757269750536,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "ad9ee066-48e0-4ecd-b9e4-bd8f51ae18de"
      },
      {
        "start": 0,
        "end": 1.7,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            20.979808647467564,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "8b152f49-ff0a-439e-a2b9-330dbbb7d118"
      },
      {
        "start": 147.316931,
        "end": 259.862,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            243.47204459742977,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "d7fdbfef-a3e7-4fae-9fdc-e1c144b864a4"
      },
      {
        "start": 981.095266,
        "end": 1008.899,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            105.96428054739198,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "831029e4-2255-4b21-bec3-5e4a591eff75"
      },
      {
        "start": 1088.43025567556,
        "end": 1090.212,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            328.4565164973542,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "c9a1fe59-6f00-41cd-b5d4-acfd0b3bb567"
      },
      {
        "start": 1520.682933,
        "end": 1597.527,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            190.94875244731634,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "a1048a91-2374-4bb0-b4df-235e7a2bd042"
      },
      {
        "start": 1899.374349,
        "end": 1953.336,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            53.440988397278545,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "d29a148b-fd97-4992-929a-b3118731dda0"
      },
      {
        "start": 2052.582002,
        "end": 2113.324,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            275.93322434724075,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "e8b50fb2-797b-4c76-985b-8e9f3e379306"
      },
      {
        "start": 2146.294929,
        "end": 2171.248,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            108.03720957097164,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "898bd800-0c90-46da-9312-c1b50de8da3a"
      },
      {
        "start": 3177.75775,
        "end": 3252.15,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            220.3968056416811,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "bee24450-6f21-43d3-98d6-01f1c8a21339"
      },
      {
        "start": 4235.139322869102,
        "end": 4592.075,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            214.88370319840556,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "0dc4a189-29c2-4c30-8fd7-3be64e9dbd7d"
      },
      {
        "start": 4636.922743,
        "end": 4687.132,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            346.4513179409182,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "a1524b6d-f70a-4cc1-8be6-aa12480705e7"
      },
      {
        "start": 5153.681629,
        "end": 5165.623,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            4.579820199247877,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "f169f346-e62c-4de8-a837-e50a53da4c89"
      },
      {
        "start": 5440.133491,
        "end": 5471.917,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            280.4879488197919,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "1eeb8e4f-6dc7-4daa-b412-64e801899e75"
      },
      {
        "start": 5871.633456,
        "end": 5900.676,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            192.61496095975804,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "8765e59b-1df3-4e0e-8a3e-a28e1835aa62"
      },
      {
        "start": 6066.210194543672,
        "end": 6079.868,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            26.364828342818896,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "9d61d5b5-c8b8-4fb3-b335-00a7845464ac"
      },
      {
        "start": 6389.02052,
        "end": 6622.807,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            327.9251853908795,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "67b2233d-10b8-48b2-9979-5f4c27307dd4"
      },
      {
        "start": 7623.402918,
        "end": 7836.642,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            63.25050390300299,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "a83fbdbb-8e90-473f-8512-a6f96f65fc23"
      },
      {
        "start": 8282.097004,
        "end": 8312.717,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            218.56053543675853,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "03cbbdfb-4eed-4fdb-8bfd-2948a0fa7c11"
      },
      {
        "start": 8876.741694,
        "name": "",
        "color": {
          "model": "hsv",
          "color": [
            300.06632712501766,
            100,
            95
          ],
          "valpha": 1
        },
        "uuid": "a768205d-841a-4b18-9b59-2777b479170a"
      }
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\Spencer\\Desktop\\Stream Videos\\Call of Duty  Modern Warfare 2019\\Call of Duty  Modern Warfare 2019 2020.05.15 - 22.44.39.01.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "8909.020000",
      "size": "51435703080",
      "bit_rate": "46187529",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "0",
        "compatible_brands": "isommp42",
        "creation_time": "2020-05-16T07:13:09.000000Z",
        "date": "2020"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}

**Comment by mifi** [comment]
Hi. Where from and how did you install LosslessCut?

**Comment by mifi** [comment]
I believe this is the same as #679. Could you try the ZIP file instead of the exe download? closing due to inactivity
