### ISSUE TITLE
Output has black video

### ISSUE THREAD

**Issue by D4nGuerrero** [mifi/lossless-cut#422]
Tried trimming an .avi file but I only get sound and no picture.

```
Error: Command failed with exit code 1: C:\Users\danny\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\node_modules\ffmpeg-static\ffmpeg.exe -hide_banner -ss 40.84084 -i D:\Video\TV\Married... with Children\Season 05\12 - Married With Who  .avi -t 21.28795 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map 0:2 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f matroska -y D:\Video\TV\Married... with Children\Season 05\12 - Married With Who  -00.00.40.840-00.01.02.128.avi
Input #0, matroska,webm, from 'D:\Video\TV\Married... with Children\Season 05\12 - Married With Who  .avi':
  Metadata:
    encoder         : libebml v1.2.3 + libmatroska v1.3.0
    creation_time   : 2012-09-03T16:14:44.000000Z
  Duration: 00:23:11.63, start: 0.000000, bitrate: 1394 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 512x384 [SAR 1:1 DAR 4:3], 29.97 fps, 29.97 tbr, 1k tbn, 29.98 tbc (default)
    Stream #0:1: Audio: mp3, 48000 Hz, stereo, fltp, 96 kb/s (default)
    Stream #0:2: Subtitle: subrip (default)
Output #0, matroska, to 'D:\Video\TV\Married... with Children\Season 05\12 - Married With Who  -00.00.40.840-00.01.02.128.avi':
  Metadata:
    creation_time   : 2012-09-03T16:14:44.000000Z
    encoder         : Lavf58.36.100
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 512x384 [SAR 1:1 DAR 4:3], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 96 kb/s (default)
    Stream #0:2: Subtitle: subrip (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
[matroska @ 000001b00ed4d3c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 000001b00ed4d3c0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
[matroska @ 000001b00ed4d3c0] Can't write packet with unknown timestamp
Error writing trailer of D:\Video\TV\Married... with Children\Season 05\12 - Married With Who  -00.00.40.840-00.01.02.128.avi: Invalid argument
frame=  301 fps=0.0 q=-1.0 Lsize=       1kB time=00:00:01.26 bitrate=   8.2kbits/s speed= 318x    
video:1794kB audio:158kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
    at makeError (C:\Users\danny\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\app.asar\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\danny\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\app.asar\node_modules\execa\index.js:114:26)
    at async _ (file:///C:/Users/danny/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:4342)
    at async L (file:///C:/Users/danny/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:5024)
    at async file:///C:/Users/danny/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:127583

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "D:\\Video\\TV\\Married... with Children\\Season 05\\12 - Married With Who  .avi",
    "fileFormat": "matroska",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "mpeg4",
        "codec_long_name": "MPEG-4 part 2",
        "profile": "Advanced Simple Profile",
        "codec_type": "video",
        "codec_time_base": "100/2997",
        "codec_tag_string": "XVID",
        "codec_tag": "0x44495658",
        "width": 512,
        "height": 384,
        "coded_width": 512,
        "coded_height": 384,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "4:3",
        "pix_fmt": "yuv420p",
        "level": 5,
        "chroma_location": "left",
        "refs": 1,
        "quarter_sample": "false",
        "divx_packed": "false",
        "r_frame_rate": "2997/100",
        "avg_frame_rate": "2997/100",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1391625,
        "duration": "1391.625000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 1,
        "codec_name": "mp3",
        "codec_long_name": "MP3 (MPEG audio layer 3)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "bit_rate": "96000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 2,
        "codec_name": "subrip",
        "codec_long_name": "SubRip subtitle",
        "codec_type": "subtitle",
        "codec_time_base": "0/1",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1391625,
        "duration": "1391.625000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "D:\\Video\\TV\\Married... with Children\\Season 05\\12 - Married With Who  .avi": {
        "0": true,
        "1": true,
        "2": true
      }
    },
    "cutSegments": [
      {
        "start": 40.84084084084084,
        "end": 62.1287954621288
      }
    ],
    "fileFormatData": {
      "filename": "D:\\Video\\TV\\Married... with Children\\Season 05\\12 - Married With Who  .avi",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "matroska,webm",
      "format_long_name": "Matroska / WebM",
      "start_time": "0.000000",
      "duration": "1391.625000",
      "size": "242628708",
      "bit_rate": "1394793",
      "probe_score": 100,
      "tags": {
        "encoder": "libebml v1.2.3 + libmatroska v1.3.0",
        "creation_time": "2012-09-03T16:14:44.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}
```

**Comment by mifi** [comment]
Try only video track, see if that works

**Comment by mifi** [comment]
Closing this due to inactivity
