### ISSUE TITLE
TypeError: Expected a finite number

### ISSUE THREAD

**Issue by bryce-lynch** [mifi/lossless-cut#436]
I tried to set cut start time in a webm video, but losslesscut said "start time must precede stop time" (I hadn't set any cut stop time yet). Then I used the cut stop icon but immediately got the following error:

```
TypeError: Expected a finite number
    at e.exports (file:///usr/share/losslesscut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:529149)
    at file:///usr/share/losslesscut/resources/app.asar/build/static/js/main.117ae403.chunk.js:1:82220
    at Array.map (<anonymous>)
    at file:///usr/share/losslesscut/resources/app.asar/build/static/js/main.117ae403.chunk.js:1:81226
    at co (file:///usr/share/losslesscut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:641405)
    at Wo (file:///usr/share/losslesscut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649670)
    at Yo (file:///usr/share/losslesscut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649489)
    at Os (file:///usr/share/losslesscut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:690143)
    at ml (file:///usr/share/losslesscut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672244)
    at fl (file:///usr/share/losslesscut/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672169)
{
  "err": {}
}
```

I can reproduce the same error by following the steps outlined above.

I'm using losslesscut v3.23.8 in arch linux.

EDIT: it seems the problem is caused by this specific webm video, as losslesscut reports 0:00:00 length, and "duration 0ms, 0frames". ffprobe has this to say:

```
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 25 
                    : Segment-Durations-Ms: 5000(r=23),5533, 
                    :  
                    : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 320x240, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)

```

**Comment by bryce-lynch** [comment]
I tried to cut the same video using ffmpeg, which said: "Output file is empty, nothing was encoded".

I guess it's an encoding/codec issue and not a bug in losslesscut. Closing.
