### ISSUE TITLE
Unable to editing OBS recorded MKV file

### ISSUE THREAD

**Issue by nigelizm** [mifi/lossless-cut#459]
TypeError: Expected a finite number
    at e.exports (file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:529149)
    at file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:82220
    at Array.map (<anonymous>)
    at file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:81226
    at co (file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:641405)
    at Wo (file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649670)
    at Yo (file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649489)
    at Os (file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:690143)
    at ml (file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672244)
    at fl (file:///C:/Users/nigel/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672169)

{
  "err": {}
}

**Comment by mifi** [comment]
What is OBS? cna you provide a sample?

**Comment by laundmo** [comment]
@mifi 
OBS is one of the most popular game streaming/recording softwares: https://obsproject.com/

@nigelizm it would probably be good for LosslessCut developers to know your OBS recording settings

**Comment by mifi** [comment]
I just tested recording OBS and for me it works. Could you try Help -> Report an error and paste it here?

BTW this issue is the same as #477 - Let's continue discussion there.
