### ISSUE TITLE
Can't scrub to point in video, and it crashes when I enter time manually

### ISSUE THREAD

**Issue by EladKarni** [mifi/lossless-cut#472]
I tried setting the time directly cause the scrubber wouldn't respond.
```
TypeError: Expected a finite number
    at e.exports (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:529149)
    at file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:82220
    at Array.map (<anonymous>)
    at file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/main.437c0011.chunk.js:1:81226
    at co (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:641405)
    at Wo (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649670)
    at Yo (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:649489)
    at Os (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:690143)
    at ml (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672244)
    at fl (file:///C:/Users/eladk/AppData/Local/Temp/1eT1HcFvyBM1bf4oP07nJ3pk5Ve/resources/app.asar/build/static/js/2.8b42b57b.chunk.js:2:672169)

{
  "err": {}
}
```

**Comment by mifi** [comment]
Where's your file from? losslesscut is having trouble with getting the duration of your file. see #477 , please comment there

**Comment by EladKarni** [comment]
> Where's your file from? losslesscut is having trouble with getting the duration of your file. see #477 , please comment there

Sorry, what did I do wrong? Why was it closed?
The file is just from my videos folder. It was recorded using OBS like every other video I have

**Comment by mifi** [comment]
I closed it because it is duplicate. Sed the other issue. Seems to be an issue with obs files. If you can provide me a sample file i can look into it
