### ISSUE TITLE
Cut and convert TS-Stream

### ISSUE THREAD

**Issue by Bikerraini** [mifi/lossless-cut#599]
I've tried to cut and convert a TS-Stream File but after clicking "Export" this text occured:

Error: Command failed with exit code 1: /Applications/LosslessCut.app/Contents/Resources/ffmpeg -hide_banner -ss 138.81072 -i /Volumes/FILMPLATTE/16.03.2020 22_27 Quigley, der Australier/16.03.2020 22_27 Quigley, der Australier.TS -t 1178.94928 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map 0:2 -map_metadata 0 -movflags +faststart -ignore_unknown -f mp4 -y /Users/rainerhein/Desktop/16.03.2020 22_27 Quigley, der Australier-00.02.18.810-00.21.57.759-seg1.mp4
[mp3float @ 0x7fd6e080ce00] Header missing
[mpeg2video @ 0x7fd6e0009000] Invalid frame dimensions 0x0.
[mp3float @ 0x7fd6e080ce00] Header missing
    Last message repeated 1 times
[mpeg2video @ 0x7fd6e0009000] Invalid frame dimensions 0x0.
    Last message repeated 1 times
[mp3float @ 0x7fd6e080ce00] Header missing
    Last message repeated 3 times
[mpeg2video @ 0x7fd6e0009000] Invalid frame dimensions 0x0.
[mp3float @ 0x7fd6e080ce00] Header missing
    Last message repeated 319 times
[mpegts @ 0x7fd6e000bc00] decoding for stream 1 failed
[mpegts @ 0x7fd6e000bc00] PES packet size mismatch
[mpegts @ 0x7fd6e000bc00] Packet corrupt (stream = 1, dts = 4164548310).
[mpegts @ 0x7fd6e000bc00] PES packet size mismatch
[mpegts @ 0x7fd6e000bc00] Packet corrupt (stream = 2, dts = 4164553536).
[mpegts @ 0x7fd6e000bc00] Could not find codec parameters for stream 1 (Audio: mp3 (mp3float), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x7fd6e000bc00] PES packet size mismatch
[mpegts @ 0x7fd6e000bc00] Packet corrupt (stream = 2, dts = 4164553536).
[mpegts @ 0x7fd6e000bc00] PES packet size mismatch
[mpegts @ 0x7fd6e000bc00] Packet corrupt (stream = 2, dts = 4164553536).
[mpegts @ 0x7fd6e000bc00] PES packet size mismatch
[mpegts @ 0x7fd6e000bc00] Packet corrupt (stream = 2, dts = 4164553536).
Input #0, mpegts, from '/Volumes/FILMPLATTE/16.03.2020 22_27 Quigley, der Australier/16.03.2020 22_27 Quigley, der Australier.TS':
  Duration: 02:42:02.40, start: 36551.079000, bitrate: 3481 kb/s
    Stream #0:0[0x5ff]: Video: mpeg2video (Main), yuv420p(tv, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Side data:
      cpb: bitrate max/min/avg: 15000000/0/0 buffer size: 1835008 vbv_delay: N/A
    Stream #0:1[0x26]: Audio: mp3, 0 channels, fltp
    Stream #0:2[0x600]: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
[mp4 @ 0x7fd6e0013200] sample rate not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
    Last message repeated 1 times
    at makeError (/Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Applications/LosslessCut.app/Contents/Resources/app.asar/node_modules/execa/index.js:114:26)
    at async L (file:///Applications/LosslessCut.app/Contents/Resources/app.asar/build/static/js/main.ebbdcb84.chunk.js:1:4780)
    at async z (file:///Applications/LosslessCut.app/Contents/Resources/app.asar/build/static/js/main.ebbdcb84.chunk.js:1:5678)
    at async file:///Applications/LosslessCut.app/Contents/Resources/app.asar/build/static/js/main.ebbdcb84.chunk.js:1:156563

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "/Volumes/FILMPLATTE/16.03.2020 22_27 Quigley, der Australier/16.03.2020 22_27 Quigley, der Australier.TS",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "mpeg2video",
        "codec_long_name": "MPEG-2 video",
        "profile": "Main",
        "codec_type": "video",
        "codec_time_base": "1/25",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 720,
        "height": 576,
        "coded_width": 0,
        "coded_height": 0,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "64:45",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 8,
        "color_range": "tv",
        "chroma_location": "left",
        "field_order": "tt",
        "refs": 1,
        "id": "0x5ff",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/90000",
        "start_pts": 3289607921,
        "start_time": "36551.199122",
        "duration_ts": 875005200,
        "duration": "9722.280000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "side_data_list": [
          {
            "side_data_type": "CPB properties"
          }
        ]
      },
      {
        "index": 1,
        "codec_name": "mp3",
        "codec_long_name": "MP3 (MPEG audio layer 3)",
        "codec_type": "audio",
        "codec_time_base": "1/0",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "0",
        "channels": 0,
        "bits_per_sample": 0,
        "id": "0x26",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3289597110,
        "start_time": "36551.079000",
        "duration_ts": 874951200,
        "duration": "9721.680000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 2,
        "codec_name": "mp2",
        "codec_long_name": "MP2 (MPEG audio layer 2)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "s16p",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x600",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3289610976,
        "start_time": "36551.233067",
        "duration_ts": 874944720,
        "duration": "9721.608000",
        "bit_rate": "192000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/Volumes/FILMPLATTE/16.03.2020 22_27 Quigley, der Australier/16.03.2020 22_27 Quigley, der Australier.TS": {
        "0": true,
        "1": true,
        "2": true
      }
    },
    "cutSegments": [
      {
        "start": 138.810718,
        "end": 1317.76
      },
      {
        "start": 1822.12,
        "end": 3208.84
      },
      {
        "start": 3626.76,
        "end": 4946.04
      },
      {
        "start": 5391,
        "end": 6764.36
      },
      {
        "start": 7229.36,
        "end": 8656.16
      }
    ],
    "fileFormatData": {
      "filename": "/Volumes/FILMPLATTE/16.03.2020 22_27 Quigley, der Australier/16.03.2020 22_27 Quigley, der Australier.TS",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mpegts",
      "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
      "start_time": "36551.079000",
      "duration": "9722.400122",
      "size": "4231560128",
      "bit_rate": "3481905",
      "probe_score": 50
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "darwin",
  "version": "3.30.0"
}

**Comment by mifi** [comment]
ts is a bit quirky. I assume you tried all suggestions like disable non-essential streams/tracks etc?

**Comment by mifi** [comment]
I think the problem here is that you're trying to export to MP4 but it doesn't support all the codecs from the TS file. Closing due to inactivity.
