### ISSUE TITLE
"Can't write packet with unknown timestamp" error when trying to convert a clip to a different format

### ISSUE THREAD

**Issue by lostfictions** [mifi/lossless-cut#651]
**Describe the bug**

When I try to convert a segment in .avi format (xvid+mp3 streams) to mkv, I get the following error:

> Error: Command failed with exit code 1: /tmp/.mount_Lossle6xf8WF/resources/node_modules/ffmpeg-ffprobe-static/ffmpeg -hide_banner -ss 5000.53721 -i \<input path>.avi -t 4.58792 -avoid_negative_ts make_zero -c copy -map 0:0 -map_metadata 0 -movflags +faststart -ignore_unknown -f matroska -y \<output path>.mkv
Input #0, avi, from '\<input path>.avi':
  Metadata:
    encoder         : FairUse Wizard - http://fairusewizard.com
  Duration: 01:33:50.29, start: 0.000000, bitrate: 1264 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 624x464 [SAR 1:1 DAR 39:29], 1127 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 128 kb/s
Output #0, matroska, to '\<output path>.mkv':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 624x464 [SAR 1:1 DAR 39:29], q=2-31, 1127 kb/s, 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[matroska @ 0x6d39440] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0x6d39440] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
frame=    1 fps=0.0 q=-1.0 Lsize=       1kB time=-00:00:02.41 bitrate=N/A speed=N/A    
video:50kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
    at makeError (/tmp/.mount_Lossle6xf8WF/resources/app.asar/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/tmp/.mount_Lossle6xf8WF/resources/app.asar/node_modules/execa/index.js:114:26)
    at async R (file:///tmp/.mount_Lossle6xf8WF/resources/app.asar/build/static/js/main.8268c48f.chunk.js:1:4715)
    at async _ (file:///tmp/.mount_Lossle6xf8WF/resources/app.asar/build/static/js/main.8268c48f.chunk.js:1:5240)
    at async file:///tmp/.mount_Lossle6xf8WF/resources/app.asar/build/static/js/main.8268c48f.chunk.js:1:166527

```
{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "<input path>.avi",
    "fileFormat": "matroska",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "mpeg4",
        "codec_long_name": "MPEG-4 part 2",
        "profile": "Advanced Simple Profile",
        "codec_type": "video",
        "codec_time_base": "1001/24000",
        "codec_tag_string": "XVID",
        "codec_tag": "0x44495658",
        "width": 624,
        "height": 464,
        "coded_width": 624,
        "coded_height": 464,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "39:29",
        "pix_fmt": "yuv420p",
        "level": 5,
        "chroma_location": "left",
        "refs": 1,
        "quarter_sample": "false",
        "divx_packed": "false",
        "r_frame_rate": "24000/1001",
        "avg_frame_rate": "24000/1001",
        "time_base": "1001/24000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 134992,
        "duration": "5630.291333",
        "bit_rate": "1127259",
        "nb_frames": "134992",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 1,
        "codec_name": "mp3",
        "codec_long_name": "MP3 (MPEG audio layer 3)",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "U[0][0][0]",
        "codec_tag": "0x0055",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "3/125",
        "start_pts": 0,
        "start_time": "0.000000",
        "bit_rate": "128000",
        "nb_frames": "234595",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "<input path>.avi": {
        "0": true,
        "1": false
      }
    },
    "cutSegments": [
      {
        "start": 5000.537208333333,
        "end": 5005.125125
      }
    ],
    "fileFormatData": {
      "filename": "<input path>.avi",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "avi",
      "format_long_name": "AVI (Audio Video Interleaved)",
      "start_time": "0.000000",
      "duration": "5630.291333",
      "size": "890019840",
      "bit_rate": "1264616",
      "probe_score": 100,
      "tags": {
        "encoder": "FairUse Wizard - http://fairusewizard.com"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "linux",
  "version": "3.32.0"
}
```

I've attempted to disable audio output and have toggled between normal and keyframe cutting with no success. I've also tried a different export format, which didn't help either. The only other issue I can find with a similar error message is the unresolved #422.

This is on Ubuntu 20.04, using the LosslessCut 3.32.0 AppImage.

**Comment by mifi** [comment]
A quick google finds this: https://trac.ffmpeg.org/ticket/3339

Does it happen even if you don't cut anything? Only change format? (e.g clear all cut segments)

**Comment by mifi** [comment]
closing due to inactivity
