### ISSUE TITLE
Cannot seem to trim Zoom MP4

### ISSUE THREAD

**Issue by rap2021** [mifi/lossless-cut#679]
Trying to cut a Zoom video mp4.  Top and tailed it but on Export, failed.  Tried outputting to original format as well as MOV and MKV.  All 3 failed.  Here is a report:

Error: Command failed with ENOENT: C:\Users\ROBPOR~1\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\node_modules\ffmpeg-static\ffmpeg.exe -hide_banner -ss 895.20000 -i F:\My Documents\Zoom\2021-02-22 10.55.11 Rob Poretti's Personal Meeting Room 3900457609\zoom_0.mp4 -t 3616.77461 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -ignore_unknown -f mp4 -y F:\My Documents\Zoom\2021-02-22 10.55.11 Rob Poretti's Personal Meeting Room 3900457609\zoom_0-00.14.55.200-01.15.11.974.mp4
spawn C:\Users\ROBPOR~1\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\node_modules\ffmpeg-static\ffmpeg.exe ENOENT
The system cannot find the path specified.
    at notFoundError (C:\Users\ROBPOR~1\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\app.asar\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\ROBPOR~1\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\app.asar\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\ROBPOR~1\AppData\Local\Temp\1eT1HcFvyBM1bf4oP07nJ3pk5Ve\resources\app.asar\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

{
  "err": {
    "code": "ENOENT",
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false
  },
  "state": {
    "filePath": "F:\\My Documents\\Zoom\\2021-02-22 10.55.11 Rob Poretti's Personal Meeting Room 3900457609\\zoom_0.mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/32000",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "32000",
        "channels": 1,
        "channel_layout": "mono",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/32000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 150581248,
        "duration": "4705.664000",
        "bit_rate": "126250",
        "max_bit_rate": "150000",
        "nb_frames": "147052",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-02-22T17:26:35.000000Z",
          "language": "und",
          "handler_name": "AAC audio"
        }
      },
      {
        "index": 1,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/50",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 2368,
        "height": 1080,
        "coded_width": 2368,
        "coded_height": 1088,
        "has_b_frames": 0,
        "pix_fmt": "yuv420p",
        "level": 51,
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/30000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 141170400,
        "duration": "4705.680000",
        "bit_rate": "725896",
        "bits_per_raw_sample": "8",
        "nb_frames": "117642",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-02-22T17:26:35.000000Z",
          "language": "und",
          "handler_name": "H.264/AVC video",
          "encoder": "AVC Coding"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "F:\\My Documents\\Zoom\\2021-02-22 10.55.11 Rob Poretti's Personal Meeting Room 3900457609\\zoom_0.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 895.2,
        "end": 4511.974609
      }
    ],
    "fileFormatData": {
      "filename": "F:\\My Documents\\Zoom\\2021-02-22 10.55.11 Rob Poretti's Personal Meeting Room 3900457609\\zoom_0.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "4705.680000",
      "size": "502496604",
      "bit_rate": "854280",
      "probe_score": 100,
      "tags": {
        "major_brand": "mp42",
        "minor_version": "0",
        "compatible_brands": "isommp42",
        "creation_time": "2021-02-22T17:26:35.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  }
}

**Comment by mifi** [comment]
I'm not sure what happened here. Could you try the ZIP file instead of the exe download? https://github.com/mifi/lossless-cut/releases/tag/v3.34.3

**Comment by mifi** [comment]
closing due to inactivity

**Comment by rap2021** [comment]
It is interesting how I get a notification when you close the link; due to inactivity.  But no notifications when a post is made, so that I might review it… 

 

That might be an “OK” outcome for you; but for me, it meant I went looking for another tool that worked with Zoom.  Sorry, but I got no activity on your end, so I had to go elsewhere.  

 

Good luck.

 

Rob

 

 

_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

Rob Poretti                     CEL.905.510.6785

 <http://www.porettiprod.com/> Poretti Productions

_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

**Comment by mifi** [comment]
Oh, maybe github had some issues then, or it went into your spam mail. No worries. If you would like to try with losslesscut again, just report back and I can reopen the issue.
