### ISSUE TITLE
Long path Path causes error

### ISSUE THREAD

**Issue by jddcef** [mifi/lossless-cut#745]
Hi, I have an error when working on a long/deep path.

If I move the file to c:\temp\t.mp4 it works fine.

Could you improve the handling of this so that it is clear how to fix the issue? 

Great software by the way.

CHeers

See:
Error: Command failed with exit code 1: F:\Software\Media Picture and Audio\LosslessCut-win mp3 mp4 splitter\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -i C:\Users\Jesus\OneDrive\Seminary2\Homilies and Reflections\Retreats\St Pauls - morning day of recollection 20 March 2021\Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now Rosemary Siemens (Voice_Piano) (240p_30fps_H264-128kbit_AAC).mp4 -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags use_metadata_tags -movflags +faststart -ignore_unknown -f mp4 -y C:\Users\Jesus\OneDrive\Seminary2\Homilies and Reflections\Retreats\St Pauls - morning day of recollection 20 March 2021\Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now Rosemary Siemens (Voice_Piano) (240p_30fps_H264-128kbit_AAC)-00.00.00.000-00.05.23.687.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Jesus\OneDrive\Seminary2\Homilies and Reflections\Retreats\St Pauls - morning day of recollection 20 March 2021\Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now Rosemary Siemens (Voice_Piano) (240p_30fps_H264-128kbit_AAC).mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now! Rosemary Siemens (Voice/Piano)
    artist          : Rosemary Siemens
    date            : 2020
    encoder         : Lavf58.39.101
    comment         : https://www.youtube.com/watch?v=twKIbIvmUQQ
  Duration: 00:05:23.69, start: 0.000000, bitrate: 375 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 426x240 [SAR 1:1 DAR 71:40], 238 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
C:\Users\Jesus\OneDrive\Seminary2\Homilies and Reflections\Retreats\St Pauls - morning day of recollection 20 March 2021\Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now Rosemary Siemens (Voice_Piano) (240p_30fps_H264-128kbit_AAC)-00.00.00.000-00.05.23.687.mp4: No such file or directory
    at makeError (F:\Software\Media Picture and Audio\LosslessCut-win mp3 mp4 splitter\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (F:\Software\Media Picture and Audio\LosslessCut-win mp3 mp4 splitter\resources\app.asar\node_modules\execa\index.js:114:26)
    at async g (file:///F:/Software/Media%20Picture%20and%20Audio/LosslessCut-win%20mp3%20mp4%20splitter/resources/app.asar/build/static/js/main.356c3555.chunk.js:1:61744)
    at async file:///F:/Software/Media%20Picture%20and%20Audio/LosslessCut-win%20mp3%20mp4%20splitter/resources/app.asar/build/static/js/main.356c3555.chunk.js:1:61947
    at async file:///F:/Software/Media%20Picture%20and%20Audio/LosslessCut-win%20mp3%20mp4%20splitter/resources/app.asar/build/static/js/main.356c3555.chunk.js:1:175726

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "C:\\Users\\Jesus\\OneDrive\\Seminary2\\Homilies and Reflections\\Retreats\\St Pauls - morning day of recollection 20 March 2021\\Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now Rosemary Siemens (Voice_Piano) (240p_30fps_H264-128kbit_AAC).mp4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "Main",
        "codec_type": "video",
        "codec_time_base": "1/60",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 426,
        "height": 240,
        "coded_width": 432,
        "coded_height": 240,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "71:40",
        "pix_fmt": "yuv420p",
        "level": 21,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "30/1",
        "time_base": "1/15360",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 4971008,
        "duration": "323.633333",
        "bit_rate": "238975",
        "bits_per_raw_sample": "8",
        "nb_frames": "9709",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "ISO Media file produced by Google Inc."
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/44100",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 14274560,
        "duration": "323.686168",
        "bit_rate": "127999",
        "max_bit_rate": "127999",
        "nb_frames": "13940",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "ISO Media file produced by Google Inc."
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\Jesus\\OneDrive\\Seminary2\\Homilies and Reflections\\Retreats\\St Pauls - morning day of recollection 20 March 2021\\Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now Rosemary Siemens (Voice_Piano) (240p_30fps_H264-128kbit_AAC).mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\Jesus\\OneDrive\\Seminary2\\Homilies and Reflections\\Retreats\\St Pauls - morning day of recollection 20 March 2021\\Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now Rosemary Siemens (Voice_Piano) (240p_30fps_H264-128kbit_AAC).mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "323.687000",
      "size": "15181343",
      "bit_rate": "375210",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "title": "Heartfelt Hymn “I Need Thee Every Hour” What The World Needs Now! Rosemary Siemens (Voice/Piano)",
        "artist": "Rosemary Siemens",
        "date": "2020",
        "encoder": "Lavf58.39.101",
        "comment": "https://www.youtube.com/watch?v=twKIbIvmUQQ"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.36.0"
}

**Comment by mifi** [comment]
could the issue be due to the special quotes `“`? e.g. `“I Need Thee Every Hour”`. Does it work if you remove those?

**Comment by jddcef** [comment]
Nope, it's not the quotes `"`, it works fine with that name with quotes when it's in a shorter folder depth or path.
I tested it now, it's caused by too long a path and filename combined. > 255 or such.

**Comment by mifi** [comment]
Ok, I'm thinking this is related to some windows file system issue. Which version of windows are you running? And what is the file system on c:?

**Comment by jddcef** [comment]
It's NTFS on Windows 10  20H2.
It seems it's some weird issue in windows: https://stackoverflow.com/questions/1857335/is-there-any-length-limits-of-file-path-in-ntfs

**Comment by mifi** [comment]
I have found that the issue is that ffmpeg doesn't seem to support paths longer than 260 on Windows. There's still an open issue:

- https://trac.ffmpeg.org/ticket/8885?cversion=1&cnum_hist=2

Seems like a workaround is to add a prefix `\\?` before the path. Not sure if this works with ffmpeg. Someone with ffmpeg on windows needs to test this. e.g.:

`c:\mymedia` -> `\\?\c:\mymedia`

- https://emby.media/community/index.php?/topic/91634-problem-long-pathslong-filename-259-characters-ffprobe-error/

**Comment by mifi** [comment]
Have now added a check for output file length on windows

**Comment by jddcef** [comment]
> Seems like a workaround is to add a prefix `\\?` before the path. Not sure if this works with ffmpeg. Someone with ffmpeg on windows needs to test this. e.g.:
> 
> `c:\mymedia` -> `\\?\c:\mymedia`

I can't seem to add the prefix without it saying folder name not valid..
And I can't see anyway in the app to manually edit the output path for example to add the "\\?\" at the front of it to test it out

**Comment by mifi** [comment]
if you can test ffmpeg.exe from the command line with such a path and confirm that it works that would be great

**Comment by jddcef** [comment]
> if you can test ffmpeg.exe from the command line with such a path and confirm that it works that would be great

`ffmpeg -i "\\?\c:\temp\t.mp4" \\?\c:\temp\t2.mp4`

Yes, this command works fine with the ffmpeg 4.4.1 in LosslessCut 3.4.2

**Comment by mifi** [comment]
I've gathered a few related issue like this inside #2891 - closing this to keep issue count down. Can still continue discussion here.
