### ISSUE TITLE
export the video failed

### ISSUE THREAD

**Issue by stefanielyq** [mifi/lossless-cut#774]
please help
thx

```
Error: Command failed with exit code 1: C:\Users\Summer\AppData\Local\Temp\1qtTF52bkFJlK61qTWXU8mImbT5\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -ss 468.68700 -i F:\集团视频\ypbase\采访正片\朱峥宸\朱铮宸 主机位2.MP4 -t 152.72564 -avoid_negative_ts make_zero -c copy -map 0:0 -map 0:1 -map_metadata 0 -movflags +faststart -ignore_unknown -f mp4 -y E:\100\朱铮宸 主机位2-00.07.48.687-00.10.21.412.MP4
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001b5f40de440] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001b5f40de440] st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'F:\集团视频\ypbase\采访正片\朱峥宸\朱铮宸 主机位2.MP4':
  Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2021-04-07T07:20:01.000000Z
  Duration: 00:16:47.04, start: 0.000000, bitrate: 52283 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/iec61966-2-4), 1920x1080 [SAR 1:1 DAR 16:9], 49492 kb/s, 50 fps, 50 tbr, 50k tbn, 100 tbc (default)
    Metadata:
      creation_time   : 2021-04-07T07:20:01.000000Z
      handler_name    : Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2021-04-07T07:20:01.000000Z
      handler_name    : Sound Media Handler
    Stream #0:2(und): Data: none (rtmd / 0x646D7472), 1228 kb/s (default)
    Metadata:
      creation_time   : 2021-04-07T07:20:01.000000Z
      handler_name    : Timed Metadata Media Handler
      timecode        : 09:24:53:14
[mp4 @ 000001b5f4970540] Could not find tag for codec pcm_s16be in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\Summer\AppData\Local\Temp\1qtTF52bkFJlK61qTWXU8mImbT5\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\Summer\AppData\Local\Temp\1qtTF52bkFJlK61qTWXU8mImbT5\resources\app.asar\node_modules\execa\index.js:114:26)
    at async g (file:///C:/Users/Summer/AppData/Local/Temp/1qtTF52bkFJlK61qTWXU8mImbT5/resources/app.asar/build/static/js/main.356c3555.chunk.js:1:61744)
    at async file:///C:/Users/Summer/AppData/Local/Temp/1qtTF52bkFJlK61qTWXU8mImbT5/resources/app.asar/build/static/js/main.356c3555.chunk.js:1:61947
    at async file:///C:/Users/Summer/AppData/Local/Temp/1qtTF52bkFJlK61qTWXU8mImbT5/resources/app.asar/build/static/js/main.356c3555.chunk.js:1:175726
    at async file:///C:/Users/Summer/AppData/Local/Temp/1qtTF52bkFJlK61qTWXU8mImbT5/resources/app.asar/build/static/js/main.356c3555.chunk.js:1:177627

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "F:\\集团视频\\ypbase\\采访正片\\朱峥宸\\朱铮宸 主机位2.MP4",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/100",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 1,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 42,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "iec61966-2-4",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "50/1",
        "avg_frame_rate": "50/1",
        "time_base": "1/50000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 50352000,
        "duration": "1007.040000",
        "bit_rate": "49492160",
        "bits_per_raw_sample": "8",
        "nb_frames": "50352",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-04-07T07:20:01.000000Z",
          "language": "und",
          "handler_name": "Video Media Handler",
          "encoder": "AVC Coding"
        }
      },
      {
        "index": 1,
        "codec_name": "pcm_s16be",
        "codec_long_name": "PCM signed 16-bit big-endian",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "twos",
        "codec_tag": "0x736f7774",
        "sample_fmt": "s16",
        "sample_rate": "48000",
        "channels": 2,
        "bits_per_sample": 16,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/48000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 48337920,
        "duration": "1007.040000",
        "bit_rate": "1536000",
        "nb_frames": "48337920",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-04-07T07:20:01.000000Z",
          "language": "und",
          "handler_name": "Sound Media Handler"
        }
      },
      {
        "index": 2,
        "codec_type": "data",
        "codec_tag_string": "rtmd",
        "codec_tag": "0x646d7472",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/50000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 50352000,
        "duration": "1007.040000",
        "bit_rate": "1228800",
        "nb_frames": "50352",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "creation_time": "2021-04-07T07:20:01.000000Z",
          "language": "und",
          "handler_name": "Timed Metadata Media Handler",
          "timecode": "09:24:53:14"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "F:\\集团视频\\ypbase\\采访正片\\朱峥宸\\朱铮宸 主机位2.MP4": {
        "0": true,
        "1": true,
        "2": false
      }
    },
    "cutSegments": [
      {
        "start": 468.687004,
        "end": 621.412647
      }
    ],
    "fileFormatData": {
      "filename": "F:\\集团视频\\ypbase\\采访正片\\朱峥宸\\朱铮宸 主机位2.MP4",
      "nb_streams": 3,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "1007.040000",
      "size": "6581391067",
      "bit_rate": "52283055",
      "probe_score": 100,
      "tags": {
        "major_brand": "XAVC",
        "minor_version": "16785407",
        "compatible_brands": "XAVCmp42iso2",
        "creation_time": "2021-04-07T07:20:01.000000Z"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.36.0"
}
```

**Comment by sleepybjr** [comment]
**Lossless-Cut** uses **FFMPEG** to cut the videos. 

According to a ticket from **FFMPEG**, MP4 specification does not allow pcm_s16be codec audio:
https://trac.ffmpeg.org/ticket/3818

This will be an issue on any video that is recorded from a Sony camera if you're attempting to cut it to another MP4.

To get around this, I have found the following workarounds:
1) Export as a MOV file.
2) Disable the sound track before exporting as an MP4.

But overall, this sounds like this is an issue that can never be fixed.

**Comment by mifi** [comment]
thx for your explanation @sleepybjr - you're right. The only thing llc can do is to give a better warning or prevent users from doing this. Closing in favor of #547

**Comment by mifi** [comment]
thx for your explanation @sleepybjr - you're right. The only thing llc can do is to give a better warning or prevent users from doing this. Closing in favor of #547
