### ISSUE TITLE
ts file wont convert to mp4

### ISSUE THREAD

**Issue by DRB540** [mifi/lossless-cut#822]
Error: Command failed with exit code 1: C:\Users\dr_d_\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -i C:\Users\dr_d_\Videos\Captures\Match of the Day 2_20210822_2230.ts -t 2238.20000 -c copy -map 0:0 -map 0:1 -map 0:3 -map_metadata 0 -movflags +faststart -ignore_unknown -f mp4 -y C:\Users\dr_d_\Videos\Captures\Match of the Day 2_20210822_2230-00.00.00.000-00.37.18.199-seg1.mp4
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000002b852843e80] decode_slice_header error
[h264 @ 000002b852843e80] no frame!
[h264 @ 000002b852843e80] mmco: unref short failure
    Last message repeated 1 times
[mpegts @ 000002b85281de00] start time for stream 8 is not set in estimate_timings_from_pts
[mpegts @ 000002b85281de00] PES packet size mismatch
[mpegts @ 000002b85281de00] Packet corrupt (stream = 1, dts = 3385727701).
[mpegts @ 000002b85281de00] Could not find codec parameters for stream 2 (Unknown: none ([17][0][0][0] / 0x0011)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 000002b85281de00] Could not find codec parameters for stream 4 (Unknown: none ([11][0][0][0] / 0x000B)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 000002b85281de00] Could not find codec parameters for stream 5 (Unknown: none ([11][0][0][0] / 0x000B)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 000002b85281de00] Could not find codec parameters for stream 6 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 000002b85281de00] Could not find codec parameters for stream 7 (Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'C:\Users\dr_d_\Videos\Captures\Match of the Day 2_20210822_2230.ts':
  Duration: 01:06:01.09, start: 33658.983344, bitrate: 6823 kb/s
  Program 17472 
  Program 17540 
    Stream #0:0[0x19c9]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x19ca](eng): Audio: aac_latm (LC) ([17][0][0][0] / 0x0011), 48000 Hz, stereo, fltp
    Stream #0:2[0x19ce](eng): Unknown: none ([17][0][0][0] / 0x0011) (visual impaired) (descriptions) (dependent)
    Stream #0:3[0x19cd](eng): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
    Stream #0:4[0x1c86]: Unknown: none ([11][0][0][0] / 0x000B)
    Stream #0:5[0x1c97]: Unknown: none ([11][0][0][0] / 0x000B)
    Stream #0:6[0x1bc4]: Unknown: none ([5][0][0][0] / 0x0005)
    Stream #0:7[0x1bc6]: Unknown: none ([5][0][0][0] / 0x0005)
  Program 17603 
  Program 17664 
  Program 17728 
  Program 18112 
  Program 20160 
  Program 20256 
  No Program
    Stream #0:8[0x12]: Data: epg
[mp4 @ 000002b853d1d240] Could not find tag for codec aac_latm in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:3 -> #0:2 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\dr_d_\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\dr_d_\AppData\Local\Temp\1voKP8pb6Lorzi7JP9v9F4pYDQ4\resources\app.asar\node_modules\execa\index.js:114:26)
    at async g (file:///C:/Users/dr_d_/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:58484)
    at async file:///C:/Users/dr_d_/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:58689
    at async file:///C:/Users/dr_d_/AppData/Local/Temp/1voKP8pb6Lorzi7JP9v9F4pYDQ4/resources/app.asar/build/static/js/main.8a3a7c71.chunk.js:1:172633

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "C:\\Users\\dr_d_\\Videos\\Captures\\Match of the Day 2_20210822_2230.ts",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/50",
        "codec_tag_string": "[27][0][0][0]",
        "codec_tag": "0x001b",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "closed_captions": 0,
        "has_b_frames": 3,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 40,
        "color_range": "tv",
        "color_space": "bt709",
        "color_transfer": "bt709",
        "color_primaries": "bt709",
        "chroma_location": "left",
        "field_order": "tt",
        "refs": 1,
        "is_avc": "false",
        "nal_length_size": "0",
        "id": "0x19c9",
        "r_frame_rate": "25/1",
        "avg_frame_rate": "25/1",
        "time_base": "1/90000",
        "start_pts": 3029395872,
        "start_time": "33659.954133",
        "duration_ts": 356410800,
        "duration": "3960.120000",
        "bits_per_raw_sample": "8",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 1,
        "codec_name": "aac_latm",
        "codec_long_name": "AAC LATM (Advanced Audio Coding LATM syntax)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[17][0][0][0]",
        "codec_tag": "0x0011",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "id": "0x19ca",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029308501,
        "start_time": "33658.983344",
        "duration_ts": 356421120,
        "duration": "3960.234667",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng"
        }
      },
      {
        "index": 2,
        "codec_tag_string": "[17][0][0][0]",
        "codec_tag": "0x0011",
        "id": "0x19ce",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029308501,
        "start_time": "33658.983344",
        "duration_ts": 356498171,
        "duration": "3961.090789",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 1,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng"
        }
      },
      {
        "index": 3,
        "codec_name": "dvb_subtitle",
        "codec_long_name": "DVB subtitles",
        "codec_type": "subtitle",
        "codec_time_base": "0/1",
        "codec_tag_string": "[6][0][0][0]",
        "codec_tag": "0x0006",
        "id": "0x19cd",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029995666,
        "start_time": "33666.618511",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng"
        }
      },
      {
        "index": 4,
        "codec_tag_string": "[11][0][0][0]",
        "codec_tag": "0x000b",
        "id": "0x1c86",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029308501,
        "start_time": "33658.983344",
        "duration_ts": 356498171,
        "duration": "3961.090789",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 5,
        "codec_tag_string": "[11][0][0][0]",
        "codec_tag": "0x000b",
        "id": "0x1c97",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029308501,
        "start_time": "33658.983344",
        "duration_ts": 356498171,
        "duration": "3961.090789",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 6,
        "codec_tag_string": "[5][0][0][0]",
        "codec_tag": "0x0005",
        "id": "0x1bc4",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029308501,
        "start_time": "33658.983344",
        "duration_ts": 356498171,
        "duration": "3961.090789",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 7,
        "codec_tag_string": "[5][0][0][0]",
        "codec_tag": "0x0005",
        "id": "0x1bc6",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029308501,
        "start_time": "33658.983344",
        "duration_ts": 356498171,
        "duration": "3961.090789",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      },
      {
        "index": 8,
        "codec_name": "epg",
        "codec_long_name": "Electronic Program Guide",
        "codec_type": "data",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "id": "0x12",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/90000",
        "start_pts": 3029308501,
        "start_time": "33658.983344",
        "duration_ts": 356498171,
        "duration": "3961.090789",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\dr_d_\\Videos\\Captures\\Match of the Day 2_20210822_2230.ts": {
        "0": true,
        "1": true,
        "2": false,
        "3": true,
        "4": false,
        "5": false,
        "6": false,
        "7": false,
        "8": false
      }
    },
    "cutSegments": [
      {
        "end": 2238.2
      },
      {
        "start": 2238.2
      }
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\dr_d_\\Videos\\Captures\\Match of the Day 2_20210822_2230.ts",
      "nb_streams": 9,
      "nb_programs": 8,
      "format_name": "mpegts",
      "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
      "start_time": "33658.983344",
      "duration": "3961.090789",
      "size": "3378401280",
      "bit_rate": "6823173",
      "probe_score": 50
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.37.0"
}

**Comment by mifi** [comment]
> [mp4 @ 000002b853d1d240] Could not find tag for codec aac_latm in stream #1, codec not currently supported in container

You could try to output MOV instead. If that doesn't work, then unfortunately you have to re-encode the audio stream or remove it

**Comment by SeaMac** [comment]
Have you tried using the free and open source "Handbrake" [https://handbrake.fr/](https://handbrake.fr/) on your .TS File? If there is an uncorrupted video in it ... Handbrake will be able to show a Preview of it ... check the Audio track THEN and see if it is OK.  Convert using the "1080 Fast" Profile to a H264 .MP4 file ... It only takes Minutes.
Handbrake is now up to version 1.4.1 ... I use it to convert .mpg (MPG1) Video (that I rip from a Live stream [Using VLC2]) to .mp4 (H264) before I feed it to Lossless Cut ... just as a matter of routine ... a normal part of the workflow. https://handbrake.fr/ 

I use 3 Excellent Open Source Programs ... VLC2's Streaming/Encoding Wizard ... Handbrake 1.4.1 ... And Lossless Cut ... to 'download/convert/and trim' Live internet Streams ... into .mp4 movies that I'll own forever. Just convert to .mp4 FIRST - Then let Lossless Cut chew on it.

**Comment by DRB540** [comment]
Thanks I'll give it a go

Dr D R Brown
________________________________

**Comment by mifi** [comment]
closing due to inactivity

**Comment by magnets110** [comment]
This is an FFMPEG or MP4 container problem. MP4 isn't compatible with AAC LATM (used in MPEGTS streams). Programs like 'XMedia Recode' will convert the AAC for you and remux in to MP4 container with original video behind the scenes.

Seamless re-encode of audio + remux video would be a neat feature.

https://superuser.com/questions/1592726/ffmpeg-aac-audio-copy

https://trac.ffmpeg.org/ticket/3244

**Comment by DRB540** [comment]
Thanks, I'll do that.



________________________________

**Comment by mifi** [comment]
you can extract the audio and video streams as separate files, then use ffmpeg to re encode the audio, then combine the files again as one file wirth video+audio
