### ISSUE TITLE
"Identifier 'extractStreams' has already been declared" when building from source on Windows

### ISSUE THREAD

**Issue by mitchcurtis** [mifi/lossless-cut#836]
When running the app built from source on Windows 10 I get a compile failure:

```
C:\dev\lossless-cut>npm start

> lossless-cut@3.38.0 start C:\dev\lossless-cut
> concurrently -k "cross-env BROWSER=none PORT=3001 DISABLE_ESLINT_PLUGIN=true react-scripts start" "wait-on http://localhost:3001 && electron ."

[0] i ｢wds｣: Project is running at http://10.0.0.6/
[0] i ｢wds｣: webpack output is served from
[0] i ｢wds｣: Content not from webpack is served from C:\dev\lossless-cut\public
[0] i ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0]
[0] Failed to compile.
[0]
[0] ./src/ffmpeg.js
[0] SyntaxError: C:\dev\lossless-cut\src\ffmpeg.js: Identifier 'extractStreams' has already been declared (357:22)
[0]
[0]   355 |
[0]   356 | // https://stackoverflow.com/questions/32922226/extract-every-audio-and-subtitles-from-a-video-with-ffmpeg
[0] > 357 | export async function extractStreams({ filePath, customOutDir, streams }) {
[0]       |                       ^
[0]   358 |   const attachmentStreams = streams.filter((s) => s.codec_type === 'attachment');
[0]   359 |   const nonAttachmentStreams = streams.filter((s) => s.codec_type !== 'attachment');
[0]   360 |
[1]
[1] Current version 3.38.0
[1] Newest version 3.38.0
[1] Added Extension: React Developer Tools
```

The complete log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\dev\\nodejs\\node.exe',
1 verbose cli   'C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lossless-cut@3.38.0~prestart: lossless-cut@3.38.0
6 info lifecycle lossless-cut@3.38.0~start: lossless-cut@3.38.0
7 verbose lifecycle lossless-cut@3.38.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle lossless-cut@3.38.0~start: PATH: C:\dev\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\dev\lossless-cut\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\dev\Strawberry\c\bin;C:\dev\Strawberry\perl\site\bin;C:\dev\Strawberry\perl\bin;C:\dev\Python;C:\Program Files\Git\cmd;C:\dev\ffmpeg\bin;;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\dev\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\dev\CMake\bin;C:\Users\Mitch\AppData\Local\Microsoft\WindowsApps;C:\Users\Mitch\AppData\Roaming\npm;C:\dev\selenium-web-drivers;
9 verbose lifecycle lossless-cut@3.38.0~start: CWD: C:\dev\lossless-cut
10 silly lifecycle lossless-cut@3.38.0~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'concurrently -k "cross-env BROWSER=none PORT=3001 DISABLE_ESLINT_PLUGIN=true react-scripts start" "wait-on http://localhost:3001 && electron ."'
10 silly lifecycle ]
11 silly lifecycle lossless-cut@3.38.0~start: Returned: code: 1  signal: null
12 info lifecycle lossless-cut@3.38.0~start: Failed to exec start script
13 verbose stack Error: lossless-cut@3.38.0 start: `concurrently -k "cross-env BROWSER=none PORT=3001 DISABLE_ESLINT_PLUGIN=true react-scripts start" "wait-on http://localhost:3001 && electron ."`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\dev\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\dev\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid lossless-cut@3.38.0
15 verbose cwd C:\dev\lossless-cut
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\dev\\nodejs\\node.exe" "C:\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error lossless-cut@3.38.0 start: `concurrently -k "cross-env BROWSER=none PORT=3001 DISABLE_ESLINT_PLUGIN=true react-scripts start" "wait-on http://localhost:3001 && electron ."`
22 error Exit status 1
23 error Failed at the lossless-cut@3.38.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mifi** [comment]
My bad. I forgot to commit some code
