### ISSUE TITLE
Can't export gif to MP4

### ISSUE THREAD

**Issue by Avasam** [mifi/lossless-cut#877]
This is the opposite of #662
I recorded a gif for a github issue, realized it's way to big, should probably be an MP4 vid instead.

**Describe the bug**
When exporting, I got an error message

**To Reproduce**
1. Open a gif
2. Click on export (select MP4)
3. See error

**Expected behavior**
Support for gif to MP4

**Screenshots**
```js
Error: Command failed with exit code 1: C:\Users\Avasam\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\node_modules\ffmpeg-ffprobe-static\ffmpeg.exe -hide_banner -i C:\Users\Avasam\Desktop\no output-00.00.02.911-00.00.12.730.gif -c copy -map 0:0 -map_metadata 0 -movflags +faststart -ignore_unknown -f mp4 -y C:\Users\Avasam\Desktop\no output-00.00.02.911-00.00.12.730-00.00.00.000-00.00.12.720.mp4
Input #0, gif, from 'C:\Users\Avasam\Desktop\no output-00.00.02.911-00.00.12.730.gif':
  Duration: 00:00:12.72, start: 0.000000, bitrate: 6648 kb/s
    Stream #0:0: Video: gif, bgra, 840x1195, 11.33 fps, 11.33 tbr, 100 tbn, 100 tbc
[mp4 @ 00000204f25bd6c0] Could not find tag for codec gif in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
    at makeError (C:\Users\Avasam\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\app.asar\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\Avasam\AppData\Local\Temp\1xMTtfMQLboD7r4ebGikn7zfvcn\resources\app.asar\node_modules\execa\index.js:114:26)
    at async O (file:///C:/Users/Avasam/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:65013)
    at async file:///C:/Users/Avasam/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:65219
    at async file:///C:/Users/Avasam/AppData/Local/Temp/1xMTtfMQLboD7r4ebGikn7zfvcn/resources/app.asar/build/static/js/main.220201e5.chunk.js:1:192095

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "C:\\Users\\Avasam\\Desktop\\no output-00.00.02.911-00.00.12.730.gif",
    "fileFormat": "mp4",
    "externalStreamFiles": [],
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "gif",
        "codec_long_name": "CompuServe GIF (Graphics Interchange Format)",
        "codec_type": "video",
        "codec_time_base": "3/34",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 840,
        "height": 1195,
        "coded_width": 840,
        "coded_height": 1195,
        "closed_captions": 0,
        "has_b_frames": 0,
        "pix_fmt": "bgra",
        "level": -99,
        "refs": 1,
        "r_frame_rate": "34/3",
        "avg_frame_rate": "34/3",
        "time_base": "1/100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 1272,
        "duration": "12.720000",
        "nb_frames": "144",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        }
      }
    ],
    "copyStreamIdsByFile": {
      "C:\\Users\\Avasam\\Desktop\\no output-00.00.02.911-00.00.12.730.gif": {
        "0": true
      }
    },
    "cutSegments": [
      {}
    ],
    "fileFormatData": {
      "filename": "C:\\Users\\Avasam\\Desktop\\no output-00.00.02.911-00.00.12.730.gif",
      "nb_streams": 1,
      "nb_programs": 0,
      "format_name": "gif",
      "format_long_name": "CompuServe Graphics Interchange Format (GIF)",
      "start_time": "0.000000",
      "duration": "12.720000",
      "size": "10570640",
      "bit_rate": "6648201",
      "probe_score": 100
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "win32",
  "version": "3.39.0"
}
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mifi** [comment]
This would be a lossy operation so it's not really losslesscut material. I'll add it as a suggestion here: #372

**Comment by mifi** [comment]
For now, can't you just use something like handbrake?

**Comment by Avasam** [comment]
Yes absolutely. There's other options and it's what I did. This tool has become my SWISS army knife so I suggested.
I should just stop recording gifs to begin with. Start as MP4, convert to gifs if/when needed.
